In [16]:
# libraries to use beforehand
import numpy as np
import numpy.random as random
import pandas as pd
from pandas import Series, DataFrame

In [17]:
# series as a data structure
series=Series([1,1,2,3,5,8,13])
print(series)
series_i=Series([1,1,2,3,5,8,13], index =['a','b','c','d','e','f','g'])
print(series_i)
print ('Element:',series_i.values)

0     1
1     1
2     2
3     3
4     5
5     8
6    13
dtype: int64
a     1
b     1
c     2
d     3
e     5
f     8
g    13
dtype: int64
Element: [ 1  1  2  3  5  8 13]

Data frame Object

In [18]:
data = {
    'ID':['100','101','102','103','104'],
    'city':['Tokyo','Osaka','kyoto','hokkaido','tokyo'],
    'Birth_year':[1990,1989,1992,1997,1982]
}
df = DataFrame(data)
print(df)

    ID      city  Birth_year
0  100     Tokyo        1990
1  101     Osaka        1989
2  102     kyoto        1992
3  103  hokkaido        1997
4  104     tokyo        1982

In [19]:
#specifying the number of columns to display
pd.set_option('display.max_columns', 50)
# specifying the maximum number of rows to display
pd.set_option('display.max_rows', 10)

In [20]:
# Downloading data from the internet
# begin by importing libraries for downloading ZIP files
#libraries for retrieving data from the web and handling zip
import requests, zipfile
from io import StringIO
import io

#specifying the url with data
url ='https://github.com/Hernan4444/MyAnimeList-Database/archive/refs/heads/master.zip'

#Acquiring data from the url
r= requests.get(url,stream=True)

#reading and extracting the zipfile
z= zipfile.ZipFile(io.BytesIO(r.content))
z.extractall()

#tree enables us to view the files in a structured manner
!sudo apt-get install tree
# viewing the files
!tree MyAnimeList-Database-master/
anime_data=pd.read_csv('MyAnimeList-Database-master/data/anime.csv')
anime_data

Reading package lists... Done
Building dependency tree... Done
Reading state information... Done
tree is already the newest version (2.1.1-2ubuntu3.24.04.2).
0 upgraded, 0 newly installed, 0 to remove and 2 not upgraded.
MyAnimeList-Database-master/
├── All Scrapping process.ipynb
├── data
│   ├── anime.csv
│   ├── animelist.csv
│   ├── anime_with_synopsis.csv
│   ├── html
│   │   ├── 1.zip
│   │   └── 5.zip
│   ├── rating_complete.csv
│   ├── readme.md
│   └── watching_status.csv
└── readme.md

3 directories, 10 files

,MAL_ID,Name,Score,Genres,English name,Japanese name,Type,Episodes,Aired,Premiered,Producers,Licensors,Studios,Source,Duration,Rating,Ranked,Popularity,Members,Favorites,Watching,Completed,On-Hold,Dropped,Plan to Watch,Score-10,Score-9,Score-8,Score-7,Score-6,Score-5,Score-4,Score-3,Score-2,Score-1
0,1,Cowboy Bebop,8.78,"Action, Adventure, Comedy, Drama, Sci-Fi, Space",Cowboy Bebop,カウボーイビバップ,TV,26,"Apr 3, 1998 to Apr 24, 1999",Spring 1998,Bandai Visual,"Funimation, Bandai Entertainment",Sunrise,Original,24 min. per ep.,R - 17+ (violence & profanity),28.0,39,1251960,61971,105808,718161,71513,26678,329800,229170.0,182126.0,131625.0,62330.0,20688.0,8904.0,3184.0,1357.0,741.0,1580.0
1,5,Cowboy Bebop: Tengoku no Tobira,8.39,"Action, Drama, Mystery, Sci-Fi, Space",Cowboy Bebop:The Movie,カウボーイビバップ 天国の扉,Movie,1,"Sep 1, 2001",Unknown,"Sunrise, Bandai Visual",Sony Pictures Entertainment,Bones,Original,1 hr. 55 min.,R - 17+ (violence & profanity),159.0,518,273145,1174,4143,208333,1935,770,57964,30043.0,49201.0,49505.0,22632.0,5805.0,1877.0,577.0,221.0,109.0,379.0
2,6,Trigun,8.24,"Action, Sci-Fi, Adventure, Comedy, Drama, Shounen",Trigun,トライガン,TV,26,"Apr 1, 1998 to Sep 30, 1998",Spring 1998,Victor Entertainment,"Funimation, Geneon Entertainment USA",Madhouse,Manga,24 min. per ep.,PG-13 - Teens 13 or older,266.0,201,558913,12944,29113,343492,25465,13925,146918,50229.0,75651.0,86142.0,49432.0,15376.0,5838.0,1965.0,664.0,316.0,533.0
3,7,Witch Hunter Robin,7.27,"Action, Mystery, Police, Supernatural, Drama, ...",Witch Hunter Robin,Witch Hunter ROBIN (ウイッチハンターロビン),TV,26,"Jul 2, 2002 to Dec 24, 2002",Summer 2002,"TV Tokyo, Bandai Visual, Dentsu, Victor Entert...","Funimation, Bandai Entertainment",Sunrise,Original,25 min. per ep.,PG-13 - Teens 13 or older,2481.0,1467,94683,587,4300,46165,5121,5378,33719,2182.0,4806.0,10128.0,11618.0,5709.0,2920.0,1083.0,353.0,164.0,131.0
4,8,Bouken Ou Beet,6.98,"Adventure, Fantasy, Shounen, Supernatural",Beet the Vandel Buster,冒険王ビィト,TV,52,"Sep 30, 2004 to Sep 29, 2005",Fall 2004,"TV Tokyo, Dentsu",Unknown,Toei Animation,Manga,23 min. per ep.,PG - Children,3710.0,4369,13224,18,642,7314,766,1108,3394,312.0,529.0,1242.0,1713.0,1068.0,634.0,265.0,83.0,50.0,27.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
17557,48481,Daomu Biji Zhi Qinling Shen Shu,Unknown,"Adventure, Mystery, Supernatural",Unknown,盗墓笔记之秦岭神树,ONA,Unknown,"Apr 4, 2021 to ?",Unknown,Unknown,Unknown,Unknown,Novel,Unknown,Unknown,Unknown,13116,354,6,0,0,0,0,354,Unknown,Unknown,Unknown,1.0,Unknown,Unknown,Unknown,Unknown,Unknown,Unknown
17558,48483,Mieruko-chan,Unknown,"Comedy, Horror, Supernatural",Unknown,見える子ちゃん,TV,Unknown,2021 to ?,Unknown,Kadokawa,Unknown,Passione,Manga,Unknown,Unknown,Unknown,17562,7010,70,14,0,14,0,6982,Unknown,Unknown,Unknown,Unknown,Unknown,Unknown,Unknown,Unknown,Unknown,Unknown
17559,48488,Higurashi no Naku Koro ni Sotsu,Unknown,"Mystery, Dementia, Horror, Psychological, Supe...",Higurashi:When They Cry – SOTSU,ひぐらしのなく頃に卒,TV,Unknown,"Jul, 2021 to ?",Summer 2021,Unknown,Unknown,Unknown,Visual novel,Unknown,R - 17+ (violence & profanity),Unknown,17558,11309,48,3,0,0,0,11306,1.0,Unknown,Unknown,Unknown,Unknown,Unknown,Unknown,Unknown,Unknown,Unknown
17560,48491,Yama no Susume: Next Summit,Unknown,"Adventure, Slice of Life, Comedy",Unknown,ヤマノススメ Next Summit,TV,Unknown,Unknown,Unknown,Kadokawa,Unknown,8bit,Manga,Unknown,PG-13 - Teens 13 or older,Unknown,17565,1386,2,13,2,2,1,1368,Unknown,Unknown,Unknown,Unknown,Unknown,Unknown,Unknown,Unknown,Unknown,Unknown
17561,48492,Scarlet Nexus,Unknown,"Action, Fantasy",Unknown,SCARLET NEXUS,TV,Unknown,"Jul, 2021 to ?",Summer 2021,Bandai Namco Arts,Unknown,Sunrise,Game,Unknown,Unknown,Unknown,17563,310,0,4,0,1,1,304,Unknown,Unknown,Unknown,Unknown,Unknown,Unknown,Unknown,Unknown,Unknown,Unknown

In [21]:
anime_data.head()
anime_data.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 17562 entries, 0 to 17561
Data columns (total 35 columns):
 #   Column         Non-Null Count  Dtype
---  ------         --------------  -----
 0   MAL_ID         17562 non-null  int64
 1   Name           17562 non-null  object
 2   Score          17562 non-null  object
 3   Genres         17562 non-null  object
 4   English name   17562 non-null  object
 5   Japanese name  17562 non-null  object
 6   Type           17562 non-null  object
 7   Episodes       17562 non-null  object
 8   Aired          17562 non-null  object
 9   Premiered      17562 non-null  object
 10  Producers      17562 non-null  object
 11  Licensors      17562 non-null  object
 12  Studios        17562 non-null  object
 13  Source         17562 non-null  object
 14  Duration       17562 non-null  object
 15  Rating         17562 non-null  object
 16  Ranked         17562 non-null  object
 17  Popularity     17562 non-null  int64
 18  Members        17562 non-null  int64
 19  Favorites      17562 non-null  int64
 20  Watching       17562 non-null  int64
 21  Completed      17562 non-null  int64
 22  On-Hold        17562 non-null  int64
 23  Dropped        17562 non-null  int64
 24  Plan to Watch  17562 non-null  int64
 25  Score-10       17562 non-null  object
 26  Score-9        17562 non-null  object
 27  Score-8        17562 non-null  object
 28  Score-7        17562 non-null  object
 29  Score-6        17562 non-null  object
 30  Score-5        17562 non-null  object
 31  Score-4        17562 non-null  object
 32  Score-3        17562 non-null  object
 33  Score-2        17562 non-null  object
 34  Score-1        17562 non-null  object
dtypes: int64(9), object(26)
memory usage: 4.7+ MB

In [22]:
# describe is used to describe basic statistics about quantitative data
anime_data.describe()

,MAL_ID,Popularity,Members,Favorites,Watching,Completed,On-Hold,Dropped,Plan to Watch
count,17562.000000,17562.000000,1.756200e+04,17562.000000,17562.000000,1.756200e+04,17562.000000,17562.000000,17562.000000
mean,21477.192347,8763.452340,3.465854e+04,457.746270,2231.487758,2.209557e+04,955.049653,1176.599533,8199.831227
std,14900.093170,5059.327278,1.252821e+05,4063.473313,14046.688133,9.100919e+04,4275.675096,4740.348653,23777.691963
min,1.000000,0.000000,1.000000e+00,0.000000,0.000000,0.000000e+00,0.000000,0.000000,1.000000
25%,5953.500000,4383.500000,3.360000e+02,0.000000,13.000000,1.110000e+02,6.000000,37.000000,112.000000
50%,22820.000000,8762.500000,2.065000e+03,3.000000,73.000000,8.175000e+02,45.000000,77.000000,752.500000
75%,35624.750000,13145.000000,1.322325e+04,31.000000,522.000000,6.478000e+03,291.750000,271.000000,4135.500000
max,48492.000000,17565.000000,2.589552e+06,183914.000000,887333.000000,2.182587e+06,187919.000000,174710.000000,425531.000000

Basic manipulation of dataframe objects

In [23]:
# Transpostition
anime_data.head().T

,0,1,2,3,4
MAL_ID,1,5,6,7,8
Name,Cowboy Bebop,Cowboy Bebop: Tengoku no Tobira,Trigun,Witch Hunter Robin,Bouken Ou Beet
Score,8.78,8.39,8.24,7.27,6.98
Genres,"Action, Adventure, Comedy, Drama, Sci-Fi, Space","Action, Drama, Mystery, Sci-Fi, Space","Action, Sci-Fi, Adventure, Comedy, Drama, Shounen","Action, Mystery, Police, Supernatural, Drama, ...","Adventure, Fantasy, Shounen, Supernatural"
English name,Cowboy Bebop,Cowboy Bebop:The Movie,Trigun,Witch Hunter Robin,Beet the Vandel Buster
...,...,...,...,...,...
Score-5,8904.0,1877.0,5838.0,2920.0,634.0
Score-4,3184.0,577.0,1965.0,1083.0,265.0
Score-3,1357.0,221.0,664.0,353.0,83.0
Score-2,741.0,109.0,316.0,164.0,50.0
Score-1,1580.0,379.0,533.0,131.0,27.0

In [24]:
anime_data['Name']

# specifying multiple coloumn names
anime_data[['Name','Score']]

#Now from a large data set specfiying the coloums to use
cols_to_use =['MAL_ID','Name','Score','Genres','Type','Aired']
anime_data_extracted= anime_data[cols_to_use]
anime_data_extracted.head()

#specifying the row name
anime_data_extracted [0:3]

,MAL_ID,Name,Score,Genres,Type,Aired
0,1,Cowboy Bebop,8.78,"Action, Adventure, Comedy, Drama, Sci-Fi, Space",TV,"Apr 3, 1998 to Apr 24, 1999"
1,5,Cowboy Bebop: Tengoku no Tobira,8.39,"Action, Drama, Mystery, Sci-Fi, Space",Movie,"Sep 1, 2001"
2,6,Trigun,8.24,"Action, Sci-Fi, Adventure, Comedy, Drama, Shounen",TV,"Apr 1, 1998 to Sep 30, 1998"

In [25]:
df = pd.DataFrame({
    'ID':[100,101,102,103],
    'city':['Tokyo','Osaka','Kyoto','Nagoya'],
    'Birth_year':[1990,1989,1992,1995],
    'Name':['Hiroshima','Akiko','Yuki','Saturo']
}, index=['a','b','c','d'])
df['a':'c']

    ID   city  Birth_year       Name
a  100  Tokyo        1990  Hiroshima
b  101  Osaka        1989      Akiko
c  102  Kyoto        1992       Yuki

In [26]:
# Ensure libraries and dataset are loaded if kernel was restarted
import pandas as pd
try:
    _ = anime_data_extracted
except NameError:
    # Re-extract if not in memory
    anime_data = pd.read_csv('MyAnimeList-Database-master/data/anime.csv')
    cols_to_use = ['MAL_ID', 'Name', 'Score', 'Genres', 'Type', 'Aired']
    anime_data_extracted = anime_data[cols_to_use]

# df loc[] allows you to retrieve a specific row and coloumn
#specifying the row name
anime_data_extracted.loc[4]

# specifying row names (if multiple)
anime_data_extracted.loc[3:8]

# specifiying coloumn multiple names
anime_data_extracted.loc[:,['Name','MAL_ID']]

#using df.iloc to specify the rows and coloumns that i need to use
anime_data.iloc[0:4,[0,2]] # first 4 rows and 1st and 3rd coloumn

   MAL_ID Score
0       1  8.78
1       5  8.39
2       6  8.24
3       7  7.27

In [27]:
import numpy as np

# creating a new coloumn
df['score'] = np.arange(4) * 10
df
print(anime_data_extracted['Score'] != 'unknown')

0        True
1        True
2        True
3        True
4        True
         ...
17557    True
17558    True
17559    True
17560    True
17561    True
Name: Score, Length: 17562, dtype: bool

In [30]:
#conditional filtering
anime_data_extracted = anime_data_extracted[anime_data_extracted['Score'] != 'unknown']
anime_data_extracted.head()

,MAL_ID,Name,Score,Genres,Type,Aired
0,1,Cowboy Bebop,8.78,"Action, Adventure, Comedy, Drama, Sci-Fi, Space",TV,"Apr 3, 1998 to Apr 24, 1999"
1,5,Cowboy Bebop: Tengoku no Tobira,8.39,"Action, Drama, Mystery, Sci-Fi, Space",Movie,"Sep 1, 2001"
2,6,Trigun,8.24,"Action, Sci-Fi, Adventure, Comedy, Drama, Shounen",TV,"Apr 1, 1998 to Sep 30, 1998"
3,7,Witch Hunter Robin,7.27,"Action, Mystery, Police, Supernatural, Drama, ...",TV,"Jul 2, 2002 to Dec 24, 2002"
4,8,Bouken Ou Beet,6.98,"Adventure, Fantasy, Shounen, Supernatural",TV,"Sep 30, 2004 to Sep 29, 2005"

In [31]:
# pulling the required coloumns including 'source' and 'members
cols_to_use_extended = ['MAL_ID', 'Name', 'Score', 'Genres', 'Type', 'Aired', 'Source', 'Members']
anime_data_extracted = anime_data[cols_to_use_extended]

# extracting data where the source is manga and must be greater than 100000
filtered_anime = anime_data_extracted[
    (anime_data_extracted['Source'] == 'Manga') &
    (anime_data_extracted['Members'] > 100000)
]

# viewing the results
display(filtered_anime.head())

,MAL_ID,Name,Score,Genres,Type,Aired,Source,Members
2,6,Trigun,8.24,"Action, Sci-Fi, Adventure, Comedy, Drama, Shounen",TV,"Apr 1, 1998 to Sep 30, 1998",Manga,558913
5,15,Eyeshield 21,7.95,"Action, Sports, Comedy, Shounen",TV,"Apr 6, 2005 to Mar 19, 2008",Manga,148259
6,16,Hachimitsu to Clover,8.06,"Comedy, Drama, Josei, Romance, Slice of Life",TV,"Apr 15, 2005 to Sep 27, 2005",Manga,214499
8,18,Initial D Fourth Stage,8.15,"Action, Cars, Sports, Drama, Seinen",TV,"Apr 17, 2004 to Feb 18, 2006",Manga,117929
9,19,Monster,8.76,"Drama, Horror, Mystery, Police, Psychological,...",TV,"Apr 7, 2004 to Sep 28, 2005",Manga,614100

In [33]:
# determining if there are any missing values in the extracted dataset
anime_data_extracted.isnull()

# checking if the main dataset has missing values
anime_data.isnull().sum()

MAL_ID          0
Name            0
Score           0
Genres          0
English name    0
               ..
Score-5         0
Score-4         0
Score-3         0
Score-2         0
Score-1         0
Length: 35, dtype: int64

In [36]:
# sorting of values
anime_data_extracted = anime_data_extracted.sort_values(by='Score', ascending=False)

# Load the other two datasets so they are defined in memory
anime_list = pd.read_csv('MyAnimeList-Database-master/data/animelist.csv')
anime_synop = pd.read_csv('MyAnimeList-Database-master/data/anime_with_synopsis.csv')

# trying to merge three data sets
print("Anime Data Length:", len(anime_data))
display(anime_data.head(3))

print("Anime List Length:", len(anime_list))
display(anime_list.head(3))

print("Anime Synopsis Length:", len(anime_synop))
display(anime_synop.head(3))

Anime Data Length: 17562

,MAL_ID,Name,Score,Genres,English name,Japanese name,Type,Episodes,Aired,Premiered,Producers,Licensors,Studios,Source,Duration,Rating,Ranked,Popularity,Members,Favorites,Watching,Completed,On-Hold,Dropped,Plan to Watch,Score-10,Score-9,Score-8,Score-7,Score-6,Score-5,Score-4,Score-3,Score-2,Score-1
0,1,Cowboy Bebop,8.78,"Action, Adventure, Comedy, Drama, Sci-Fi, Space",Cowboy Bebop,カウボーイビバップ,TV,26,"Apr 3, 1998 to Apr 24, 1999",Spring 1998,Bandai Visual,"Funimation, Bandai Entertainment",Sunrise,Original,24 min. per ep.,R - 17+ (violence & profanity),28.0,39,1251960,61971,105808,718161,71513,26678,329800,229170.0,182126.0,131625.0,62330.0,20688.0,8904.0,3184.0,1357.0,741.0,1580.0
1,5,Cowboy Bebop: Tengoku no Tobira,8.39,"Action, Drama, Mystery, Sci-Fi, Space",Cowboy Bebop:The Movie,カウボーイビバップ 天国の扉,Movie,1,"Sep 1, 2001",Unknown,"Sunrise, Bandai Visual",Sony Pictures Entertainment,Bones,Original,1 hr. 55 min.,R - 17+ (violence & profanity),159.0,518,273145,1174,4143,208333,1935,770,57964,30043.0,49201.0,49505.0,22632.0,5805.0,1877.0,577.0,221.0,109.0,379.0
2,6,Trigun,8.24,"Action, Sci-Fi, Adventure, Comedy, Drama, Shounen",Trigun,トライガン,TV,26,"Apr 1, 1998 to Sep 30, 1998",Spring 1998,Victor Entertainment,"Funimation, Geneon Entertainment USA",Madhouse,Manga,24 min. per ep.,PG-13 - Teens 13 or older,266.0,201,558913,12944,29113,343492,25465,13925,146918,50229.0,75651.0,86142.0,49432.0,15376.0,5838.0,1965.0,664.0,316.0,533.0

Anime List Length: 499

   user_id  anime_id  rating  watching_status  watched_episodes
0        0        67       9                1                 1
1        0      6702       7                1                 4
2        0       242      10                1                 4

Anime Synopsis Length: 16214

,MAL_ID,Name,Score,Genres,sypnopsis
0,1,Cowboy Bebop,8.78,"Action, Adventure, Comedy, Drama, Sci-Fi, Space","In the year 2071, humanity has colonized sever..."
1,5,Cowboy Bebop: Tengoku no Tobira,8.39,"Action, Drama, Mystery, Sci-Fi, Space","other day, another bounty—such is the life of ..."
2,6,Trigun,8.24,"Action, Sci-Fi, Adventure, Comedy, Drama, Shounen","Vash the Stampede is the man with a $$60,000,0..."

In [39]:
# data merging (inner joint)
pd.merge(anime_data_extracted, anime_synop, on='MAL_ID')

# preparing and using the left outer join two data sets
#data 1
data1 = {
    'id': ['100', '101', '102', '103', '104', '106', '108', '110', '111', '113'],
    'city': ['Tokyo', 'Osaka', 'Kyoto', 'Hokkaido', 'Tokyo', 'Tokyo', 'Osaka', 'Kyoto', 'Hokkaido', 'Tokyo'],
    'birth_year': [1990, 1989, 1992, 1997, 1982, 1991, 1988, 1990, 1988, 1990],
    'name': ['Hiroshi', 'Akiko', 'Yuki', 'Satoru', 'Steeve', 'Mituru', 'Aoi', 'Tarou', 'Suguru', 'Mitsuo']
}
df1 = DataFrame(data1)
df1

    id      city  birth_year     name
0  100     Tokyo        1990  Hiroshi
1  101     Osaka        1989    Akiko
2  102     Kyoto        1992     Yuki
3  103  Hokkaido        1997   Satoru
4  104     Tokyo        1982   Steeve
5  106     Tokyo        1991   Mituru
6  108     Osaka        1988      Aoi
7  110     Kyoto        1990    Tarou
8  111  Hokkaido        1988   Suguru
9  113     Tokyo        1990   Mitsuo

In [40]:
# preparing data set 2
data2= {
    'id': ['100', '101', '102', '105', '107'],
    'math': [50, 43, 33, 76,98],
    'english': [90, 30, 20, 50, 30],
    'sex': ['M', 'F', 'F', 'M', 'M'],
    'index_num': [0, 1, 2, 3, 4]
}
df2 = DataFrame(data2)
df2

    id  math  english sex  index_num
0  100    50       90   M          0
1  101    43       30   F          1
2  102    33       20   F          2
3  105    76       50   M          3
4  107    98       30   M          4

In [42]:
# data merging
pd.merge (df1,df2, how='left')

pd.merge(df1,df2,how = 'outer')

     id      city  birth_year     name  math  english  sex  index_num
0   100     Tokyo      1990.0  Hiroshi  50.0     90.0    M        0.0
1   101     Osaka      1989.0    Akiko  43.0     30.0    F        1.0
2   102     Kyoto      1992.0     Yuki  33.0     20.0    F        2.0
3   103  Hokkaido      1997.0   Satoru   NaN      NaN  NaN        NaN
4   104     Tokyo      1982.0   Steeve   NaN      NaN  NaN        NaN
..  ...       ...         ...      ...   ...      ...  ...        ...
7   107       NaN         NaN      NaN  98.0     30.0    M        4.0
8   108     Osaka      1988.0      Aoi   NaN      NaN  NaN        NaN
9   110     Kyoto      1990.0    Tarou   NaN      NaN  NaN        NaN
10  111  Hokkaido      1988.0   Suguru   NaN      NaN  NaN        NaN
11  113     Tokyo      1990.0   Mitsuo   NaN      NaN  NaN        NaN

[12 rows x 8 columns]

In [44]:
# handling data
# deleting
anime_data_extracted.drop(index=[0,2]).head()

,MAL_ID,Name,Score,Genres,Type,Aired,Source,Members
8781,22821,Himitsukessha Taka no Tsume EX,Unknown,"Comedy, Parody, Super Power",TV,"Apr 11, 2014 to Mar 6, 2015",Unknown,355
10365,30125,Bad Badtz-Maru no Otoko Dokyou no Omoiyari,Unknown,Comedy,OVA,"Oct 21, 1995",Unknown,202
10357,30117,Monpy,Unknown,"Kids, Adventure",TV,1997,Unknown,112
10358,30118,Futari wa Nakayoshi: Goo to Sue,Unknown,"Kids, Slice of Life",TV,"Apr, 1991 to Feb, 1994",Unknown,152
10359,30119,Yowamushi Monsters,Unknown,Kids,TV,"Dec 25, 2012 to ?",Original,226